Refactor crontab generator algorithm

diff --git a/src/usr/local/lib/acme/acme-setup b/src/usr/local/lib/acme/acme-setup
--- a/src/usr/local/lib/acme/acme-setup
+++ b/src/usr/local/lib/acme/acme-setup
@@ -82,42 +82,54 @@ if [ ! -f "/etc/crontabs/acme" ]; then
 
     __crontabs() {
         local HASH="$(md5sum - <<< "$1")"
-        local MONTHLY_CRON="$2" MONTHLY_CMD="$3"
-        local DAILY_CRON="$4" DAILY_CMD="$5"
+        shift
 
-        # TIME represents the `n`th minute of the month (e.g. 12,345 is the 9th day at 13:45)
+        # TIME represents the `n`th minute of the month (e.g., 12,345 is the 9th day at 13:45)
         # since the cronjob wouldn't run in February otherwise, we accept the 28th day max,
         # thus we perform an euclidean division by 28 days * 24 hours * 60 minutes = 40,320
+        # day of month, weekday, hour, and minute are whole dividers and thus derived directly
         local TIME=$(( 0x${HASH:0:14} % 40320 ))
 
-        # DAILY_TIME_OFFSET represents a `n` minute offset from TIME's time of day
-        # the daily cronjob shall run between 00:30 and 23:29 hours later than the monthly cronjob,
-        # thus we perform an euclidean division by 24 hours * 60 minutes - 2 * 30 minutes = 1,380
-        # yielding some value between 00:00 and 22:59 hours, thus adding another 30 minutes
-        local DAILY_TIME_OFFSET=$(( 0x${HASH:16:14} % 1380 + 30 ))
+        # TIME_MONTH represents the `n`th month of the year (e.g., 3 is March)
+        # thus we perform an euclidean division by 12 (months)
+        local TIME_MONTH=$(( 0x${HASH:14:4} % 12 + 1 ))
 
-        if ! __is_cron_valid "$MONTHLY_CRON"; then
-            local MONTHLY_DAY=$(( TIME / 1440 + 1 ))
-            local MONTHLY_HOUR=$(( TIME % 1440 / 60 ))
-            local MONTHLY_MINUTE=$(( TIME % 1440 % 60 ))
-            MONTHLY_CRON="$(printf '%d %d %d * *' $MONTHLY_MINUTE $MONTHLY_HOUR $MONTHLY_DAY)"
-        fi
+        # MULTI_JOB_OFFSET is used to offset the execution time ob multiple cronjobs
+        # all cronjobs shall run between 10 and 20 minutes after each other,
+        # thus we perform an euclidean division by 10 minutes and add another 10 minutes
+        # we use Bash's pseudo random number generator and seed it by an incrementing
+        # MULTI_JOB_SEED to calculate (pseudo) random, but stable per-cronjob offsets
+        local MULTI_JOB_OFFSET=0 MULTI_JOB_SEED=$(( 0x${HASH:18:4} ))
 
-        if ! __is_cron_valid "$DAILY_CRON"; then
-            local DAILY_TIME=$(( ( TIME % 1440 + DAILY_TIME_OFFSET ) % 1440 ))
-            local DAILY_HOUR=$(( DAILY_TIME / 60 ))
-            local DAILY_MINUTE=$(( DAILY_TIME % 60 ))
-            DAILY_CRON="$(printf '%d %d * * *' $DAILY_MINUTE $DAILY_HOUR)"
-        fi
+        local CRON_TIME= CRON_MONTH= CRON_DAY= CRON_WEEKDAY= CRON_HOUR= CRON_MINUTE=
+        while (( $# >= 2 )); do
+            if __is_cron_valid "$1"; then
+                printf '%s %s\n' "$1" "$2"
+            elif [[ "$1" =~ ^@(yearly|monthly|weekly|daily|hourly)$ ]]; then
+                CRON_TIME=$(( TIME + MULTI_JOB_OFFSET ))
+                CRON_MONTH="*"; CRON_DAY="*"; CRON_WEEKDAY="*"; CRON_HOUR="*"
+                [ "$1" != "@yearly" ] || CRON_MONTH=$TIME_MONTH
+                [ "$1" != "@monthly" ] || CRON_DAY=$(( CRON_TIME / 1440 + 1 ))
+                [ "$1" != "@weekly" ] || CRON_WEEKDAY=$(( CRON_TIME % 10080 / 1440 ))
+                [ "$1" == "@hourly" ] || CRON_HOUR=$(( CRON_TIME % 1440 / 60 ))
+                CRON_MINUTE=$(( CRON_TIME % 60 ))
 
-        printf '%s %s\n' "$MONTHLY_CRON" "$MONTHLY_CMD"
-        printf '%s %s\n' "$DAILY_CRON" "$DAILY_CMD"
+                printf '%s %s %s %s %s %s\n' "$CRON_MINUTE" "$CRON_HOUR" "$CRON_DAY" "$CRON_MONTH" "$CRON_WEEKDAY" "$2"
+
+                MULTI_JOB_SEED=$(( ++MULTI_JOB_SEED % 32768 ))
+                (( MULTI_JOB_OFFSET += $(bash -c "RANDOM=$MULTI_JOB_SEED; echo \$RANDOM") % 10 + 10 ))
+            else
+                echo "Invalid crontab: $1 $2" >&2
+                return 1
+            fi
+            shift 2
+        done
     }
 
     log "creating crontab file '/etc/crontabs/acme'..."
 
     __crontabs "$(ls -1 "/var/local/acme/live")" \
-        "${CRON_RENEW:-}" "acme-renew --all --retry --retry --clean --verbose" \
-        "${CRON_CHECK:-}" "acme-check --all --retry --retry --renew --retry-renew --retry-renew --verbose" \
+        "${CRON_RENEW:-@monthly}" "acme-renew --all --retry --retry --clean --verbose" \
+        "${CRON_CHECK:-@daily}" "acme-check --all --retry --retry --renew --retry-renew --retry-renew --verbose" \
         > "/etc/crontabs/acme"
 fi
